name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: oprypin/install-sfml@v1.2.1

      - name: Check codestyle
        run: git ls-files *.{cpp,hpp} | xargs clang-format -i && git diff --exit-code

      - name: Build application
        run: make all
